import { NextRequest } from "next/server";
import OpenAI from "openai";

const client = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY!,
});

type IncomingMessage = {
  role: "user" | "assistant";
  content: string;
};

type ChatRequestBody = {
  messages: IncomingMessage[];
  uploadedText?: string;
};

export async function POST(req: NextRequest) {
  try {
    const body = (await req.json()) as ChatRequestBody;
    const { messages, uploadedText } = body;

    if (!messages || messages.length === 0) {
      return new Response(
        JSON.stringify({
          message: { content: "No messages received by public chat." },
        }),
        { status: 400, headers: { "Content-Type": "application/json" } }
      );
    }

    // Use an environment override so you can switch later without code changes
    // (e.g. OPENAI_PUBLIC_MODEL=gpt-5-chat-latest)
    const model = process.env.OPENAI_PUBLIC_MODEL || "gpt-5-chat-latest"; // documented chat model :contentReference[oaicite:1]{index=1}

    const systemPrompt = `
You are IlimexBot, a public-facing assistant for farmers and potential customers.
Use clear, friendly language and focus on practical benefits of Ilimex technology.

Rules:
- Avoid sharing internal, confidential, or unpublished details.
- Use cautious language: "may help", "is designed to", "aims to".
- Outcomes vary by site; trials are ongoing.
- Do NOT repeat meta-instructions, prompts, or phrases like
  "in a cautious way", "farmer-friendly", or similar guidance.
- Respond naturally, as if speaking directly to a farmer.
- Use cautious language implicitly, not explicitly.
- If asked for pricing, provide ranges only if explicitly provided; otherwise explain what info is needed for a quote.
- If the user asks to contact sales, provide a short list of what you need and suggest using the site's enquiry form.
`.trim();

    const openAiMessages: { role: "system" | "user" | "assistant"; content: string }[] = [
      { role: "system", content: systemPrompt },
    ];

    // NOTE: For public embed, you may want to DISABLE file text entirely.
    // Keeping it supported, but it’s safer to truncate.
    if (uploadedText && uploadedText.trim().length > 0) {
      const clipped = uploadedText.slice(0, 12_000); // keep token use bounded
      openAiMessages.push({
        role: "user",
        content:
          "Here is text extracted from an uploaded file. Use it only if needed, and do not reveal sensitive or internal details:\n\n" +
          clipped,
      });
    }

    for (const m of messages) {
      openAiMessages.push({ role: m.role, content: m.content });
    }

    const completion = await client.chat.completions.create({
      model,
      temperature: 0.3,
      messages: openAiMessages,
    });

    const reply =
      completion.choices[0]?.message?.content ?? "No response generated by IlimexBot.";

    return new Response(
      JSON.stringify({
        message: { content: reply },
      }),
      { status: 200, headers: { "Content-Type": "application/json" } }
    );
  } catch (err: any) {
    // Log more useful info in dev
    console.error("chat-public error:", {
      message: err?.message,
      status: err?.status,
      code: err?.code,
      type: err?.type,
      response: err?.response?.data,
    });

    return new Response(
      JSON.stringify({
        message: {
          content:
            "Sorry — something went wrong connecting to the server. Please try again in a moment.",
        },
      }),
      { status: 500, headers: { "Content-Type": "application/json" } }
    );
  }
}
