import { NextRequest } from "next/server";
import OpenAI from "openai";

const client = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY!,
});

type IncomingMessage = {
  role: "user" | "assistant";
  content: string;
};

type ChatRequestBody = {
  messages: IncomingMessage[];
  uploadedText?: string;
};

export async function POST(req: NextRequest) {
  try {
    const body = (await req.json()) as ChatRequestBody;
    const { messages, uploadedText } = body;

    if (!messages || messages.length === 0) {
      return new Response(
        JSON.stringify({
          message: { content: "No messages received by public chat." },
        }),
        { status: 400, headers: { "Content-Type": "application/json" } }
      );
    }

    const systemPrompt = `
You are IlimexBot, a public-facing assistant for farmers and potential customers.
Use clear, friendly language and focus on practical benefits of Ilimex technology.
You must:
- Avoid sharing internal or unpublished details.
- Use cautious language such as "may help" or "is designed to".
- Emphasise that results can vary by farm and that trials are ongoing.
`.trim();

    const openAiMessages: { role: "system" | "user" | "assistant"; content: string }[] = [
      { role: "system", content: systemPrompt },
    ];

    if (uploadedText && uploadedText.trim().length > 0) {
      openAiMessages.push({
        role: "user",
        content: `Here is the text extracted from the uploaded file. Use it to help answer my questions, but avoid sharing anything too technical or sensitive:\n\n${uploadedText}`,
      });
    }

    for (const m of messages) {
      openAiMessages.push({
        role: m.role,
        content: m.content,
      });
    }

    const completion = await client.chat.completions.create({
      model: "gpt-5.1-mini",
      temperature: 0.3,
      messages: openAiMessages,
    });

    const reply = completion.choices[0]?.message?.content ?? "No response generated by IlimexBot.";

    return new Response(
      JSON.stringify({
        message: { content: reply },
      }),
      { status: 200, headers: { "Content-Type": "application/json" } }
    );
  } catch (err) {
    console.error("chat-public error:", err);
    return new Response(
      JSON.stringify({
        message: {
          content:
            "Sorry, there was an internal error handling your request in public mode.",
        },
      }),
      { status: 500, headers: { "Content-Type": "application/json" } }
    );
  }
}
