// src/data/ilimex-knowledge.ts

import fs from "fs";
import path from "path";

export interface IlimexEmbeddingRecord {
  id: string;
  title: string;
  text: string;
  embedding: number[];
}

let ilimexEmbeddingCache: IlimexEmbeddingRecord[] | null = null;

/**
 * Load Ilimex embeddings from the JSON file generated by
 * scripts/generate-ilimex-embeddings.js
 *
 * Uses an in-memory cache so we don't hit the filesystem on every request.
 */
export function getIlimexEmbeddings(): IlimexEmbeddingRecord[] {
  if (ilimexEmbeddingCache) {
    return ilimexEmbeddingCache;
  }

  const embeddingsPath = path.join(
    process.cwd(),
    "src",
    "data",
    "ilimex-embeddings.json",
  );

  if (!fs.existsSync(embeddingsPath)) {
    throw new Error(
      `ilimex-embeddings.json not found at ${embeddingsPath}. ` +
        `Run "node scripts/generate-ilimex-embeddings.js" first.`,
    );
  }

  const fileContents = fs.readFileSync(embeddingsPath, "utf8");
  ilimexEmbeddingCache = JSON.parse(
    fileContents,
  ) as IlimexEmbeddingRecord[];

  return ilimexEmbeddingCache;
}
